spring.application.name=natura.post

# Configuração de conexão do Neon
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do HikariCP
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.max-lifetime=600000

# JPA
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

spring.config.import=optional:file:.env[.properties]
